import { doc, getDoc, setDoc, deleteDoc, collection, getDocs } from "../lib/embeddedDb";
import { db } from '../lib/firebase';
import { University, Campus, FoodZone, Vendor, FoodCategory, MenuItem } from '../types';

export const FALLBACK_MTU_UNIVERSITY: University & { address?: string } = {
  id: 'uni_mtu',
  name: 'Mountain Top University',
  short_name: 'MTU',
  slug: 'mountain-top-university',
  state: 'Ogun',
  city: 'Ibafo / Prayer City',
  country: 'Nigeria',
  description: 'Mountain Top University is a private university located at Prayer City along the Lagos-Ibadan Expressway in Ogun State, Nigeria.',
  address: 'Kilometre 12, Lagos-Ibadan Expressway, Prayer City, Ogun State, Nigeria',
  logo_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=200',
  cover_image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200',
  latitude: 6.7628,
  longitude: 3.3768,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const FALLBACK_MTU_CAMPUS: Campus = {
  id: 'campus_mtu_main',
  university_id: 'uni_mtu',
  name: 'Main Campus',
  slug: 'main-campus',
  description: 'Mountain Top University main campus at Prayer City, Ogun State.',
  address: 'Kilometre 12, Lagos-Ibadan Expressway, Prayer City, Ogun State, Nigeria',
  latitude: 6.7628,
  longitude: 3.3768,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const VENDOR_CREATION_ADMIN_PIN = '100110011001';

export const FALLBACK_MTU_VENDORS: (Vendor & {
  menu_status?: string;
  price_status?: string;
  verification_status?: string;
  image_source_type?: string;
  license?: string;
  source_credit?: string;
})[] = [
  {
    id: 'vendor_stand1_bunlab',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: 'zone_central',
    name: 'Stand-1(Bunlab)',
    slug: 'stand-1-bunlab',
    description: 'Freshly baked campus pastries, burgers, Shawarma wraps, meat pies, and snacks.',
    vendor_type: 'fast_food',
    logo_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&q=80&w=800',
    address: 'Stand 1, MTU Central Food Court',
    latitude: 6.7625,
    longitude: 3.3765,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.9,
    review_count: 156,
    opening_time: '08:00',
    closing_time: '21:30',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_multigrace',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: 'zone_central',
    name: 'Multi-grace',
    slug: 'multi-grace',
    description: 'Famous MTU Smoky Jollof Rice, Fried Rice, tender chicken, crispy turkey, and daily student specials.',
    vendor_type: 'cafeteria',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    address: 'Multi-grace Stand, Student Arcade',
    latitude: 6.7628,
    longitude: 3.3768,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.8,
    review_count: 142,
    opening_time: '07:00',
    closing_time: '21:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_kitchen3',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: 'zone_central',
    name: 'Kitchen3',
    slug: 'kitchen3',
    description: 'Authentic piping hot Amala, Pounded Yam, rich Egusi, Ewedu, Gbegiri & tender goat meat.',
    vendor_type: 'buka',
    logo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    address: 'Kitchen 3 Stand, East Dining Court',
    latitude: 6.7630,
    longitude: 3.3770,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 5.0,
    review_count: 188,
    opening_time: '08:00',
    closing_time: '20:30',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_mama_fruits',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: 'zone_central',
    name: 'Mama Fruits',
    slug: 'mama-fruits',
    description: 'Fresh organic fruit salads, detox parfaits, ice-cold zobo, fruit juices, smoothies, and healthy snacks.',
    vendor_type: 'drinks',
    logo_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800',
    address: 'Mama Fruits Pavilion, Library Walkway',
    latitude: 6.7627,
    longitude: 3.3769,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.9,
    review_count: 115,
    opening_time: '08:00',
    closing_time: '20:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_kitchen5_mummy_daddy',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: 'zone_central',
    name: 'Kitchen5(Mummy and Daddy)',
    slug: 'kitchen5-mummy-and-daddy',
    description: 'Homestyle comfort meals, crispy fried yam, spicy egg sauce, peppered beef suya, BBQ wings, and sides.',
    vendor_type: 'cafeteria',
    logo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    address: 'Kitchen 5 Stand, Central Pavilion',
    latitude: 6.7632,
    longitude: 3.3760,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.9,
    review_count: 134,
    opening_time: '08:30',
    closing_time: '22:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_MTU_CANTEEN = FALLBACK_MTU_VENDORS[0];

/**
 * Intelligent matcher to resolve user full name / stand string to one of the 5 official vendors.
 */
export function matchOfficialVendor(inputNameOrId?: string) {
  if (!inputNameOrId) return null;
  const str = inputNameOrId.trim();
  const clean = str.toLowerCase().replace(/[^a-z0-9]/g, '');

  for (const v of FALLBACK_MTU_VENDORS) {
    const vCleanId = v.id.toLowerCase().replace(/[^a-z0-9]/g, '');
    const vCleanName = v.name.toLowerCase().replace(/[^a-z0-9]/g, '');
    if (v.id === str || vCleanId === clean || vCleanName === clean) return v;
    if (vCleanName.includes(clean) || clean.includes(vCleanName)) return v;
  }

  // Stand-1 (Bunlab)
  if (clean.includes('bunlab') || clean.includes('stand1') || clean.includes('stand-1')) {
    return FALLBACK_MTU_VENDORS.find(v => v.id === 'vendor_stand1_bunlab') || null;
  }
  // Multi-grace
  if (clean.includes('multigrace') || clean.includes('multi-grace') || (clean.includes('multi') && clean.includes('grace'))) {
    return FALLBACK_MTU_VENDORS.find(v => v.id === 'vendor_multigrace') || null;
  }
  // Kitchen3
  if (clean.includes('kitchen3') || clean.includes('kitchen-3')) {
    return FALLBACK_MTU_VENDORS.find(v => v.id === 'vendor_kitchen3') || null;
  }
  // Mama Fruits
  if (clean.includes('mamafruit') || clean.includes('mama-fruit') || clean.includes('fruits')) {
    return FALLBACK_MTU_VENDORS.find(v => v.id === 'vendor_mama_fruits') || null;
  }
  // Kitchen5 (Mummy and Daddy)
  if (clean.includes('kitchen5') || clean.includes('kitchen-5') || clean.includes('mummy') || clean.includes('daddy')) {
    return FALLBACK_MTU_VENDORS.find(v => v.id === 'vendor_kitchen5_mummy_daddy') || null;
  }

  return null;
}

export const FALLBACK_MTU_MENU_ITEMS: MenuItem[] = [
  // 1. Stand-1(Bunlab)
  {
    id: 'dish_bunlab_burger',
    vendor_id: 'vendor_stand1_bunlab',
    category_id: 'cat_fast_food',
    name: 'Bunlab Double Beef Burger & Crispy Fries',
    slug: 'bunlab-double-beef-burger-fries',
    description: 'Fresh grilled double beef patty on toasted sesame bun with melted cheese, lettuce, and crispy french fries.',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600',
    base_price: 2800,
    price: 2800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '10-15 mins',
    rating: 4.9,
    review_count: 94,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_bunlab_shawarma',
    vendor_id: 'vendor_stand1_bunlab',
    category_id: 'cat_snacks',
    name: 'Jumbo Chicken Shawarma Roll',
    slug: 'jumbo-chicken-shawarma-roll',
    description: 'Warm grilled pita wrap loaded with shredded chicken, creamy garlic mayo, sausage, and crunchy cabbage.',
    image_url: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&q=80&w=600',
    base_price: 2500,
    price: 2500,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '8-12 mins',
    rating: 5.0,
    review_count: 128,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_bunlab_meatpie',
    vendor_id: 'vendor_stand1_bunlab',
    category_id: 'cat_snacks',
    name: 'Flaky Beef Meat Pie & Glazed Doughnut',
    slug: 'flaky-beef-meat-pie-doughnut',
    description: 'Freshly baked buttery pastry filled with minced beef and potato chunks, with a sweet glazed doughnut.',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=600',
    base_price: 1000,
    price: 1000,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '3 mins',
    rating: 4.8,
    review_count: 64,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_bunlab_sausageroll',
    vendor_id: 'vendor_stand1_bunlab',
    category_id: 'cat_snacks',
    name: 'Golden Sausage Roll & Chilled Drink Combo',
    slug: 'golden-sausage-roll-drink-combo',
    description: 'Crisp pastry roll with seasoned sausage filling served with chilled soda.',
    image_url: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=600',
    base_price: 900,
    price: 900,
    available: true,
    student_friendly: true,
    preparation_time: '3 mins',
    rating: 4.7,
    review_count: 42,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_bunlab_pizza',
    vendor_id: 'vendor_stand1_bunlab',
    category_id: 'cat_fast_food',
    name: 'Cheesy Pepperoni Pizza Slice',
    slug: 'cheesy-pepperoni-pizza-slice',
    description: 'Large oven-baked pizza slice loaded with mozzarella cheese and spicy pepperoni slices.',
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&q=80&w=600',
    base_price: 1800,
    price: 1800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '5-8 mins',
    rating: 4.9,
    review_count: 81,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 2. Multi-grace
  {
    id: 'dish_mg_jollof_chicken',
    vendor_id: 'vendor_multigrace',
    category_id: 'cat_rice',
    name: 'Multi-grace Smoky Party Jollof & Fried Chicken',
    slug: 'multigrace-smoky-party-jollof-chicken',
    description: 'Authentic firewood-infused jollof rice served with seasoned fried chicken and sweet fried plantain.',
    image_url: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&q=80&w=600',
    base_price: 1800,
    price: 1800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '10-15 mins',
    rating: 4.9,
    review_count: 142,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mg_fried_rice_turkey',
    vendor_id: 'vendor_multigrace',
    category_id: 'cat_rice',
    name: 'Special Fried Rice with Crispy Turkey & Plantain',
    slug: 'special-fried-rice-crispy-turkey',
    description: 'Wok-tossed seasoned fried rice with veggies, sweet corn, and golden fried turkey cut.',
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600',
    base_price: 2200,
    price: 2200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '10-15 mins',
    rating: 4.8,
    review_count: 98,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mg_beans_dodo',
    vendor_id: 'vendor_multigrace',
    category_id: 'cat_beans',
    name: 'Ewa Aganyin with Golden Dodo & Boiled Egg',
    slug: 'ewa-aganyin-dodo-egg',
    description: 'Mashed honey beans topped with fiery caramelized spicy palm oil sauce, fried plantains, and a boiled egg.',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    base_price: 1200,
    price: 1200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '5-10 mins',
    rating: 4.9,
    review_count: 85,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mg_spag_sausage',
    vendor_id: 'vendor_multigrace',
    category_id: 'cat_pasta',
    name: 'Stir-Fried Spaghetti with Sausage & Egg',
    slug: 'stir-fried-spaghetti-sausage-egg',
    description: 'Rich tomato stir-fried spaghetti with sliced sausages, sweet bell peppers, and boiled egg.',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600',
    base_price: 1400,
    price: 1400,
    available: true,
    student_friendly: true,
    preparation_time: '10 mins',
    rating: 4.7,
    review_count: 53,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mg_ayamase',
    vendor_id: 'vendor_multigrace',
    category_id: 'cat_rice',
    name: 'Spicy White Rice with Designer Ayamase Sauce',
    slug: 'spicy-white-rice-ayamase-sauce',
    description: 'Steamed white rice paired with green pepper Designer ofada/ayamase sauce, boiled egg, and beef cuts.',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    base_price: 2000,
    price: 2000,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '10 mins',
    rating: 5.0,
    review_count: 77,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 3. Kitchen3
  {
    id: 'dish_k3_amala_abula',
    vendor_id: 'vendor_kitchen3',
    category_id: 'cat_swallow',
    name: 'Kitchen3 Hot Amala with Abula & Goat Meat',
    slug: 'kitchen3-hot-amala-abula-goat-meat',
    description: 'Smooth hot yam flour swallow (Amala) drenched in abula (Gbegiri & Ewedu) with tender goat meat.',
    image_url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&q=80&w=600',
    base_price: 2200,
    price: 2200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '10-15 mins',
    rating: 5.0,
    review_count: 140,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k3_pounded_yam',
    vendor_id: 'vendor_kitchen3',
    category_id: 'cat_swallow',
    name: 'Pounded Yam with Rich Egusi & Assorted Meat',
    slug: 'kitchen3-pounded-yam-rich-egusi',
    description: 'Fluffy pounded yam paired with thick spinach melon seed soup (Egusi) and assorted offal & beef cuts.',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=600',
    base_price: 2400,
    price: 2400,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '12-18 mins',
    rating: 4.9,
    review_count: 88,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k3_semo_eforiro',
    vendor_id: 'vendor_kitchen3',
    category_id: 'cat_soups',
    name: 'Steamed Semo with Fresh Efo Riro & Catfish',
    slug: 'kitchen3-semo-efo-riro-catfish',
    description: 'Smooth semolina swallow paired with savory vegetable stew packed with dried crayfish, ponmo, and catfish.',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=600',
    base_price: 2500,
    price: 2500,
    available: true,
    student_friendly: false,
    preparation_time: '15 mins',
    rating: 4.8,
    review_count: 65,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k3_catfish_peppersoup',
    vendor_id: 'vendor_kitchen3',
    category_id: 'cat_soups',
    name: 'Fresh Catfish Pepper Soup with Boiled Yam',
    slug: 'kitchen3-fresh-catfish-peppersoup',
    description: 'Hot aromatic herbal broth loaded with fresh point-and-kill catfish cut and boiled yam cubes.',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=600',
    base_price: 2600,
    price: 2600,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '15-20 mins',
    rating: 4.9,
    review_count: 73,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 4. Mama Fruits
  {
    id: 'dish_mf_parfait',
    vendor_id: 'vendor_mama_fruits',
    category_id: 'cat_fruits',
    name: 'Signature Greek Yogurt Fruit Parfait with Granola',
    slug: 'mama-fruits-parfait-granola',
    description: 'Layered thick greek yogurt with diced strawberries, kiwi, apples, honey drizzle, and crunchy almond granola.',
    image_url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    base_price: 1800,
    price: 1800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '3-5 mins',
    rating: 5.0,
    review_count: 145,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mf_zobo',
    vendor_id: 'vendor_mama_fruits',
    category_id: 'cat_drinks',
    name: 'Organic Spiced Zobo with Ginger & Pineapple (50cl)',
    slug: 'mama-fruits-organic-spiced-zobo',
    description: 'Naturally brewed chilled hibiscus tea steeped with fresh ginger root, pineapple, cloves, and mint.',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600',
    base_price: 600,
    price: 600,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '2 mins',
    rating: 4.9,
    review_count: 180,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mf_watermelon_juice',
    vendor_id: 'vendor_mama_fruits',
    category_id: 'cat_drinks',
    name: 'Fresh Cold-Pressed Watermelon-Pineapple Juice (50cl)',
    slug: 'fresh-cold-pressed-watermelon-juice',
    description: '100% pure fresh cold-pressed watermelon and ripe pineapple juice with zero added sugar.',
    image_url: 'https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&q=80&w=600',
    base_price: 1000,
    price: 1000,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '2 mins',
    rating: 4.9,
    review_count: 92,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mf_chapman',
    vendor_id: 'vendor_mama_fruits',
    category_id: 'cat_drinks',
    name: 'Signature Nigerian Iced Chapman',
    slug: 'mama-fruits-signature-iced-chapman',
    description: 'Refreshing fruit soda blend infused with angostura bitters, grenadine, lemon slices, and cucumber ribbon.',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    base_price: 900,
    price: 900,
    available: true,
    student_friendly: true,
    preparation_time: '3 mins',
    rating: 4.8,
    review_count: 67,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mf_fruit_bowl',
    vendor_id: 'vendor_mama_fruits',
    category_id: 'cat_fruits',
    name: 'Jumbo Mixed Fresh Fruit Bowl',
    slug: 'jumbo-mixed-fresh-fruit-bowl',
    description: 'Chilled freshly sliced watermelon, sweet pawpaw, crisp gala apples, and seedless grapes.',
    image_url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&q=80&w=600',
    base_price: 1200,
    price: 1200,
    available: true,
    student_friendly: true,
    preparation_time: '3 mins',
    rating: 4.9,
    review_count: 76,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 5. Kitchen5(Mummy and Daddy)
  {
    id: 'dish_k5_rice_stew',
    vendor_id: 'vendor_kitchen5_mummy_daddy',
    category_id: 'cat_rice',
    name: 'Mummy & Daddy Homestyle Rice & Pepper Chicken Stew',
    slug: 'mummy-daddy-homestyle-rice-chicken-stew',
    description: 'Fluffy white rice served with rich seasoned tomato-pepper stew, fried chicken, and dodo.',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    base_price: 1800,
    price: 1800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '10 mins',
    rating: 4.9,
    review_count: 110,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k5_yam_egg',
    vendor_id: 'vendor_kitchen5_mummy_daddy',
    category_id: 'cat_yam',
    name: 'Crispy Golden Fried Yam with Spicy Egg Sauce',
    slug: 'crispy-golden-fried-yam-egg-sauce',
    description: 'Golden fried yam fingers with hot scrambled pepper egg sauce and fried plantains.',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=600',
    base_price: 1200,
    price: 1200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '8-12 mins',
    rating: 4.8,
    review_count: 75,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k5_beef_suya',
    vendor_id: 'vendor_kitchen5_mummy_daddy',
    category_id: 'cat_beef',
    name: 'Peppered Beef Suya & Roasted Onion Pack',
    slug: 'peppered-beef-suya-roasted-onion',
    description: 'Thinly sliced boneless beef skewers roasted over open coals and dusted with authentic yaji spice and sliced onions.',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    base_price: 1600,
    price: 1600,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '8-12 mins',
    rating: 5.0,
    review_count: 94,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k5_bbq_wings',
    vendor_id: 'vendor_kitchen5_mummy_daddy',
    category_id: 'cat_chicken',
    name: 'Flame-Grilled BBQ Chicken Wings (6 pcs)',
    slug: 'flame-grilled-bbq-chicken-wings',
    description: 'Six juicy grilled chicken wings glazed in sticky sweet-and-spicy barbecue sauce.',
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&q=80&w=600',
    base_price: 2300,
    price: 2300,
    available: true,
    student_friendly: false,
    preparation_time: '12-16 mins',
    rating: 4.9,
    review_count: 67,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_k5_beans_dodo',
    vendor_id: 'vendor_kitchen5_mummy_daddy',
    category_id: 'cat_beans',
    name: 'Sweet Fried Plantain (Dodo) & Honey Beans Bowl',
    slug: 'fried-plantain-dodo-beans-bowl',
    description: 'Slow-simmered sweet honey beans stew paired with hot golden fried plantain chunks.',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    base_price: 1300,
    price: 1300,
    available: true,
    student_friendly: true,
    preparation_time: '5 mins',
    rating: 4.8,
    review_count: 58,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_MTU_CATEGORIES: FoodCategory[] = [
  { id: 'cat_breakfast', name: 'Breakfast', slug: 'breakfast', description: 'Breakfast foods available at MTU food facilities.', is_active: true, image_url: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_rice', name: 'Rice', slug: 'rice', description: 'Rice dishes', is_active: true, image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_pasta', name: 'Pasta', slug: 'pasta', description: 'Pasta meals', is_active: true, image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_noodles', name: 'Noodles', slug: 'noodles', description: 'Noodle dishes', is_active: true, image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_beans', name: 'Beans', slug: 'beans', description: 'Beans meals', is_active: true, image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_yam', name: 'Yam', slug: 'yam', description: 'Boiled and fried yam options', is_active: true, image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_plantain', name: 'Plantain', slug: 'plantain', description: 'Fried and boiled plantains', is_active: true, image_url: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_swallow', name: 'Swallow', slug: 'swallow', description: 'Traditional swallows', is_active: true, image_url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_soups', name: 'Soups', slug: 'soups', description: 'Authentic Nigerian soups', is_active: true, image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_chicken', name: 'Chicken', slug: 'chicken', description: 'Grilled and fried chicken options', is_active: true, image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_beef', name: 'Beef', slug: 'beef', description: 'Beef options', is_active: true, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fish', name: 'Fish', slug: 'fish', description: 'Fresh and fried fish options', is_active: true, image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_egg', name: 'Egg', slug: 'egg', description: 'Boiled and fried eggs', is_active: true, image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_snacks', name: 'Snacks', slug: 'snacks', description: 'Pastries and light snacks', is_active: true, image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fast_food', name: 'Fast Food', slug: 'fast-food', description: 'Quick bites and fast food', is_active: true, image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_drinks', name: 'Drinks', slug: 'drinks', description: 'Beverages and refreshments', is_active: true, image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fruits', name: 'Fruits', slug: 'fruits', description: 'Fresh fruit options', is_active: true, image_url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_desserts', name: 'Desserts', slug: 'desserts', description: 'Sweet treats and desserts', is_active: true, image_url: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_coffee', name: 'Coffee', slug: 'coffee', description: 'Brewed coffee options', is_active: true, image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_tea', name: 'Tea', slug: 'tea', description: 'Hot and cold tea drinks', is_active: true, image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=300' },
];

async function withTimeout<T>(promise: Promise<T>, ms = 3500): Promise<T> {
  let timer: any;
  const timeoutPromise = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error('Firestore operation timeout')), ms);
  });
  try {
    return await Promise.race([promise, timeoutPromise]);
  } finally {
    clearTimeout(timer);
  }
}

export async function initializeDatabaseSeed() {
  try {
    console.log('Ensuring Mountain Top University (MTU) 5 Official Vendors in Database...');

    // 2. University: Mountain Top University
    await setDoc(doc(db, 'universities', FALLBACK_MTU_UNIVERSITY.id), FALLBACK_MTU_UNIVERSITY);

    // 3. Campus: Main Campus
    await setDoc(doc(db, 'campuses', FALLBACK_MTU_CAMPUS.id), FALLBACK_MTU_CAMPUS);

    // 4. MTU 5 Food Stands & Vendors
    for (const v of FALLBACK_MTU_VENDORS) {
      await setDoc(doc(db, 'vendors', v.id), v, { merge: true });
      await setDoc(doc(db, 'restaurants', v.id), {
        id: v.id,
        name: v.name,
        description: v.description || '',
        logo_url: v.logo_url,
        cover_image_url: v.cover_image_url,
        review_count: v.review_count || 0,
        rating: v.rating || 4.9,
        delivery_fee: 200,
        estimated_delivery_time: '10-20 min',
        minimum_order: 500,
        address: v.address,
        latitude: v.latitude,
        longitude: v.longitude,
        is_open: true,
        created_at: v.created_at
      }, { merge: true });
    }

    // 5. Food Categories for MTU
    for (const c of FALLBACK_MTU_CATEGORIES) {
      await setDoc(doc(db, 'food_categories', c.id), c, { merge: true });
      await setDoc(doc(db, 'categories', c.id), c, { merge: true });
    }

    // 6. Food Menu Items for the 5 Vendors
    for (const item of FALLBACK_MTU_MENU_ITEMS) {
      await setDoc(doc(db, 'menu_items', item.id), item, { merge: true });
    }

    console.log('Mountain Top University (MTU) 5 Official Vendors successfully synchronized.');
  } catch (error: any) {
    console.info('Database seed notice:', error?.message || error);
  }
}


