import { doc, getDoc, setDoc, deleteDoc, collection, getDocs } from "../lib/embeddedDb";
import { db } from '../lib/firebase';
import { University, Campus, FoodZone, Vendor, FoodCategory, MenuItem } from '../types';

export const FALLBACK_MTU_UNIVERSITY: University & { address?: string } = {
  id: 'uni_mtu',
  name: 'Mountain Top University',
  short_name: 'MTU',
  slug: 'mountain-top-university',
  state: 'Ogun',
  city: 'Ibafo / Prayer City',
  country: 'Nigeria',
  description: 'Mountain Top University is a private university located at Prayer City along the Lagos-Ibadan Expressway in Ogun State, Nigeria.',
  address: 'Kilometre 12, Lagos-Ibadan Expressway, Prayer City, Ogun State, Nigeria',
  logo_url: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&q=80&w=200',
  cover_image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200',
  latitude: 6.7628,
  longitude: 3.3768,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const FALLBACK_MTU_CAMPUS: Campus = {
  id: 'campus_mtu_main',
  university_id: 'uni_mtu',
  name: 'Main Campus',
  slug: 'main-campus',
  description: 'Mountain Top University main campus at Prayer City, Ogun State.',
  address: 'Kilometre 12, Lagos-Ibadan Expressway, Prayer City, Ogun State, Nigeria',
  latitude: 6.7628,
  longitude: 3.3768,
  is_active: true,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const FALLBACK_MTU_VENDORS: (Vendor & {
  menu_status?: string;
  price_status?: string;
  verification_status?: string;
  image_source_type?: string;
  license?: string;
  source_credit?: string;
})[] = [
  {
    id: 'vendor_mtu_canteen',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: '',
    name: 'MTU Students Central Canteen',
    slug: 'mtu-students-canteen',
    description: 'The primary student canteen serving hot Nigerian breakfast, lunch, and daily campus specials.',
    vendor_type: 'cafeteria',
    logo_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&q=80&w=800',
    address: 'Central Students Complex, Mountain Top University',
    latitude: 6.7628,
    longitude: 3.3768,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.8,
    review_count: 142,
    opening_time: '07:00',
    closing_time: '21:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_mtu_buka',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: '',
    name: 'Mama Tee Kitchen & Buka',
    slug: 'mama-tee-kitchen',
    description: 'Authentic piping-hot Amala, Pounded Yam, rich Egusi, and tender goat meat stew.',
    vendor_type: 'buka',
    logo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&q=80&w=800',
    address: 'East Hall Stand, Prayer City Campus',
    latitude: 6.7630,
    longitude: 3.3770,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.9,
    review_count: 88,
    opening_time: '08:00',
    closing_time: '20:30',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_mtu_pastries',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: '',
    name: 'Campus Pastries & Shawarma Hub',
    slug: 'campus-pastries-shawarma',
    description: 'Juicy jumbo shawarma wraps, beef pies, burgers, pizzas, and fresh baked snack combos.',
    vendor_type: 'shawarma',
    logo_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&q=80&w=800',
    address: 'Student Activity Arcade, MTU',
    latitude: 6.7625,
    longitude: 3.3765,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.7,
    review_count: 95,
    opening_time: '09:00',
    closing_time: '22:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_mtu_grills',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: '',
    name: 'MTU Sizzle Grills & Suya Point',
    slug: 'mtu-sizzle-grills',
    description: 'Peppered beef suya, smoky BBQ chicken wings, and spicy asun goat meat.',
    vendor_type: 'fast_food',
    logo_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&q=80&w=800',
    address: 'Sports Pavilion Court, MTU',
    latitude: 6.7632,
    longitude: 3.3760,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.9,
    review_count: 67,
    opening_time: '12:00',
    closing_time: '22:30',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
  {
    id: 'vendor_mtu_drinks',
    university_id: 'uni_mtu',
    campus_id: 'campus_mtu_main',
    food_zone_id: '',
    name: 'Chill Spot Smoothies & Cold Drinks',
    slug: 'chill-spot-drinks',
    description: 'Chilled spiced zobo, ice-cold chapman, fresh fruit parfaits, and refreshing milkshakes.',
    vendor_type: 'drinks',
    logo_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=200',
    cover_image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=800',
    address: 'Library Walkway, MTU',
    latitude: 6.7627,
    longitude: 3.3769,
    delivery_available: true,
    pickup_available: true,
    is_open: true,
    is_verified: true,
    is_active: true,
    rating: 4.8,
    review_count: 53,
    opening_time: '08:30',
    closing_time: '20:00',
    verification_status: 'verified',
    menu_status: 'active',
    price_status: 'verified',
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_MTU_CANTEEN = FALLBACK_MTU_VENDORS[0];

export const FALLBACK_MTU_MENU_ITEMS: MenuItem[] = [
  // 1. MTU Students Canteen Dishes
  {
    id: 'dish_mtu_jollof_chicken',
    vendor_id: 'vendor_mtu_canteen',
    category_id: 'cat_rice',
    name: 'Smoky Party Jollof Rice & Fried Chicken',
    slug: 'smoky-party-jollof-rice-chicken',
    description: 'Authentic firewood-infused jollof rice served with seasoned fried chicken and sweet fried plantain.',
    image_url: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&q=80&w=600',
    base_price: 1800,
    price: 1800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '10-15 mins',
    calories: 680,
    protein: 34,
    carbs: 85,
    fat: 22,
    fiber: 5,
    portion_description: '1 plate (Jollof rice + 1 pc Chicken + Plantains)',
    allergens: ['Soy'],
    ingredients: ['Long grain rice', 'Tomatoes', 'Bell peppers', 'Chicken', 'Ripe plantain', 'Vegetable oil', 'Spices'],
    dietary_tags: ['Halal', 'High Protein', 'Student Favorite'],
    rating: 4.9,
    review_count: 94,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mtu_fried_rice_beef',
    vendor_id: 'vendor_mtu_canteen',
    category_id: 'cat_rice',
    name: 'Special Fried Rice & Peppered Beef',
    slug: 'special-fried-rice-peppered-beef',
    description: 'Wok-tossed seasoned fried rice with fresh veggies, sweet corn, liver, and succulent peppered beef.',
    image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=600',
    base_price: 2000,
    price: 2000,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '10-15 mins',
    calories: 720,
    protein: 38,
    carbs: 78,
    fat: 26,
    fiber: 6,
    portion_description: '1 plate (Wok Fried Rice + Peppered Beef cuts)',
    allergens: ['Soy', 'Egg'],
    ingredients: ['Parboiled rice', 'Carrots', 'Green peas', 'Sweet corn', 'Beef', 'Liver', 'Vegetable oil'],
    dietary_tags: ['Halal', 'High Protein'],
    rating: 4.8,
    review_count: 72,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mtu_beans_dodo',
    vendor_id: 'vendor_mtu_canteen',
    category_id: 'cat_beans',
    name: 'Ewa Aganyin with Golden Dodo & Egg',
    slug: 'ewa-aganyin-dodo-egg',
    description: 'Mashed honey beans topped with fiery caramelized spicy palm oil sauce, fried plantains, and a boiled egg.',
    image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=600',
    base_price: 1200,
    price: 1200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '5-10 mins',
    calories: 590,
    protein: 28,
    carbs: 64,
    fat: 18,
    fiber: 14,
    portion_description: '1 hearty bowl (Mashed beans + Aganyin sauce + Dodo + 1 Egg)',
    allergens: ['Egg'],
    ingredients: ['Honey beans', 'Dried red chili peppers', 'Onions', 'Palm oil', 'Plantain', 'Egg'],
    dietary_tags: ['High Fiber', 'Vegetarian Option'],
    rating: 4.9,
    review_count: 85,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mtu_spag_sauce',
    vendor_id: 'vendor_mtu_canteen',
    category_id: 'cat_pasta',
    name: 'Stir-Fried Spaghetti with Sausage & Egg',
    slug: 'stir-fried-spaghetti-sausage',
    description: 'Rich tomato stir-fried spaghetti with sliced sausages, sweet bell peppers, and boiled egg.',
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=600',
    base_price: 1400,
    price: 1400,
    available: true,
    student_friendly: true,
    preparation_time: '10 mins',
    calories: 630,
    protein: 22,
    carbs: 88,
    fat: 19,
    fiber: 4,
    portion_description: '1 plate (Pasta + Beef sausage slices + Egg)',
    allergens: ['Gluten', 'Egg'],
    ingredients: ['Durum wheat spaghetti', 'Tomato paste', 'Beef sausages', 'Bell peppers', 'Egg', 'Vegetable oil'],
    dietary_tags: ['Quick Prep'],
    rating: 4.7,
    review_count: 53,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_mtu_yam_egg',
    vendor_id: 'vendor_mtu_canteen',
    category_id: 'cat_yam',
    name: 'Crispy Fried Yam with Spicy Egg Sauce',
    slug: 'crispy-fried-yam-egg-sauce',
    description: 'Golden fried yam fingers with hot scrambled pepper egg sauce and fried plantains.',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=600',
    base_price: 1100,
    price: 1100,
    available: true,
    student_friendly: true,
    preparation_time: '10-12 mins',
    calories: 520,
    protein: 16,
    carbs: 72,
    fat: 17,
    fiber: 6,
    portion_description: '6 fried yam slices + Scrambled pepper egg sauce',
    allergens: ['Egg'],
    ingredients: ['White yam', 'Eggs', 'Fresh tomatoes', 'Scotch bonnet pepper', 'Vegetable oil'],
    dietary_tags: ['Vegetarian Friendly'],
    rating: 4.8,
    review_count: 41,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 2. Mama Tee Kitchen & Buka Dishes
  {
    id: 'dish_buka_amala_ewedu',
    vendor_id: 'vendor_mtu_buka',
    category_id: 'cat_swallow',
    name: 'Hot Amala with Gbegiri, Ewedu & Goat Meat',
    slug: 'hot-amala-gbegiri-ewedu-goat-meat',
    description: 'Smooth hot yam flour swallow (Amala) drenched in abula (Gbegiri & Ewedu) with tender goat meat.',
    image_url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&q=80&w=600',
    base_price: 2200,
    price: 2200,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '10-15 mins',
    calories: 610,
    protein: 36,
    carbs: 68,
    fat: 18,
    fiber: 8,
    portion_description: '2 wraps Amala + Abula soup + 1 large Goat meat cut',
    allergens: [],
    ingredients: ['Yam flour (Elubo)', 'Ewedu leaves', 'Gbegiri beans', 'Goat meat', 'Locust beans (Iru)', 'Palm oil'],
    dietary_tags: ['Traditional', 'High Protein', 'Gluten Free'],
    rating: 5.0,
    review_count: 110,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_buka_pounded_yam',
    vendor_id: 'vendor_mtu_buka',
    category_id: 'cat_swallow',
    name: 'Pounded Yam with Rich Egusi & Assorted Meat',
    slug: 'pounded-yam-rich-egusi',
    description: 'Fluffy pounded yam paired with thick spinach melon seed soup (Egusi) and assorted offal & beef cuts.',
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=600',
    base_price: 2400,
    price: 2400,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '12-18 mins',
    calories: 780,
    protein: 42,
    carbs: 76,
    fat: 32,
    fiber: 7,
    portion_description: '2 wraps Pounded yam + Egusi soup + Assorted meat',
    allergens: ['Fish', 'Crustaceans'],
    ingredients: ['Pounded yam', 'Melon seeds (Egusi)', 'Spinach', 'Beef & Tripe', 'Stockfish', 'Dried crayfish'],
    dietary_tags: ['High Energy', 'High Protein'],
    rating: 4.9,
    review_count: 78,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_buka_efo_riro',
    vendor_id: 'vendor_mtu_buka',
    category_id: 'cat_soups',
    name: 'Steamed Semo with Rich Efo Riro & Catfish',
    slug: 'semo-efo-riro-catfish',
    description: 'Smooth semolina swallow paired with savory vegetable stew packed with dried crayfish, ponmo, and catfish.',
    image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=600',
    base_price: 2500,
    price: 2500,
    available: true,
    student_friendly: false,
    preparation_time: '15 mins',
    calories: 640,
    protein: 40,
    carbs: 70,
    fat: 20,
    fiber: 9,
    portion_description: '2 wraps Semo + Fresh Efo Riro + Point & Kill Catfish',
    allergens: ['Fish', 'Gluten', 'Crustaceans'],
    ingredients: ['Semolina', 'Green shoko spinach', 'Catfish', 'Ponmo', 'Crayfish', 'Palm oil'],
    dietary_tags: ['Hearty', 'High Iron'],
    rating: 4.8,
    review_count: 45,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 3. Campus Pastries & Shawarma Hub Dishes
  {
    id: 'dish_pastry_double_shawarma',
    vendor_id: 'vendor_mtu_pastries',
    category_id: 'cat_snacks',
    name: 'Double Jumbo Beef & Chicken Shawarma Wrap',
    slug: 'double-jumbo-shawarma-wrap',
    description: 'Warm grilled pita wrap loaded with shredded chicken & beef, creamy garlic mayo, sausage, and crunchy cabbage.',
    image_url: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?auto=format&fit=crop&q=80&w=600',
    base_price: 2500,
    price: 2500,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '10-15 mins',
    calories: 740,
    protein: 36,
    carbs: 58,
    fat: 38,
    fiber: 4,
    portion_description: '1 double jumbo grilled wrap (10 inch)',
    allergens: ['Gluten', 'Dairy', 'Egg'],
    ingredients: ['Pita bread', 'Chicken breast', 'Beef', 'Sausage', 'Cabbage', 'Garlic mayonnaise', 'Ketchup'],
    dietary_tags: ['Halal', 'High Protein'],
    rating: 4.9,
    review_count: 128,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_pastry_meat_pie_combo',
    vendor_id: 'vendor_mtu_pastries',
    category_id: 'cat_snacks',
    name: 'Flaky Beef Meat Pie & Glazed Doughnut Combo',
    slug: 'flaky-meat-pie-doughnut-combo',
    description: 'Freshly baked buttery pastry filled with minced beef and potato chunks, with a sweet glazed doughnut.',
    image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=600',
    base_price: 900,
    price: 900,
    available: true,
    student_friendly: true,
    preparation_time: '3 mins',
    calories: 480,
    protein: 14,
    carbs: 62,
    fat: 22,
    fiber: 3,
    portion_description: '1 Meat pie + 1 Glazed doughnut',
    allergens: ['Gluten', 'Dairy', 'Egg'],
    ingredients: ['Wheat flour', 'Minced beef', 'Potatoes', 'Butter', 'Sugar', 'Yeast'],
    dietary_tags: ['Grab & Go'],
    rating: 4.7,
    review_count: 64,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_pastry_burger_fries',
    vendor_id: 'vendor_mtu_pastries',
    category_id: 'cat_fast_food',
    name: 'Crispy Chicken Burger & Seasoned Fries',
    slug: 'crispy-chicken-burger-fries',
    description: 'Golden fried chicken breast patty on toasted sesame bun with melted cheese, lettuce, and crispy french fries.',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&q=80&w=600',
    base_price: 2800,
    price: 2800,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: false,
    preparation_time: '12-18 mins',
    calories: 820,
    protein: 38,
    carbs: 82,
    fat: 36,
    fiber: 5,
    portion_description: '1 Crispy Burger + Regular Fries box',
    allergens: ['Gluten', 'Dairy', 'Sesame', 'Egg'],
    ingredients: ['Sesame brioche bun', 'Chicken patty', 'Cheddar cheese', 'Crispy fries', 'Lettuce', 'Burger sauce'],
    dietary_tags: ['Halal', 'Chef Special'],
    rating: 4.8,
    review_count: 91,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 4. MTU Sizzle Grills & Suya Dishes
  {
    id: 'dish_grill_suya_pack',
    vendor_id: 'vendor_mtu_grills',
    category_id: 'cat_beef',
    name: 'Peppered Beef Suya & Roasted Onion Pack',
    slug: 'peppered-beef-suya-pack',
    description: 'Thinly sliced boneless beef skewers roasted over open coals and dusted with authentic yaji spice and sliced onions.',
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600',
    base_price: 1500,
    price: 1500,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '8-12 mins',
    rating: 5.0,
    review_count: 89,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_grill_bbq_wings',
    vendor_id: 'vendor_mtu_grills',
    category_id: 'cat_chicken',
    name: 'Flame-Grilled BBQ Chicken Wings (6 pcs)',
    slug: 'flame-grilled-bbq-chicken-wings',
    description: 'Six juicy grilled chicken wings glazed in sticky sweet-and-spicy campus barbecue sauce.',
    image_url: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?auto=format&fit=crop&q=80&w=600',
    base_price: 2300,
    price: 2300,
    available: true,
    student_friendly: false,
    preparation_time: '12-16 mins',
    rating: 4.9,
    review_count: 57,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },

  // 5. Chill Spot Smoothies & Cold Drinks
  {
    id: 'dish_drink_chilled_zobo',
    vendor_id: 'vendor_mtu_drinks',
    category_id: 'cat_drinks',
    name: 'Organic Spiced Zobo with Ginger (50cl)',
    slug: 'organic-spiced-zobo-ginger',
    description: 'Naturally brewed hibiscus tea steeped with fresh ginger root, pineapple peels, cloves, and mint.',
    image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=600',
    base_price: 500,
    price: 500,
    available: true,
    popular: true,
    is_popular: true,
    student_friendly: true,
    preparation_time: '2 mins',
    rating: 4.9,
    review_count: 140,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
  {
    id: 'dish_drink_iced_chapman',
    vendor_id: 'vendor_mtu_drinks',
    category_id: 'cat_drinks',
    name: 'Signature Nigerian Iced Chapman',
    slug: 'signature-nigerian-iced-chapman',
    description: 'Refreshing fruit soda blend infused with angostura bitters, grenadine, lemon slices, and cucumber ribbon.',
    image_url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600',
    base_price: 800,
    price: 800,
    available: true,
    student_friendly: true,
    preparation_time: '3 mins',
    rating: 4.8,
    review_count: 67,
    verification_status: 'verified',
    status: 'Published',
    created_at: new Date().toISOString(),
  },
];

export const FALLBACK_MTU_CATEGORIES: FoodCategory[] = [
  { id: 'cat_breakfast', name: 'Breakfast', slug: 'breakfast', description: 'Breakfast foods available at MTU food facilities.', is_active: true, image_url: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_rice', name: 'Rice', slug: 'rice', description: 'Rice dishes', is_active: true, image_url: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_pasta', name: 'Pasta', slug: 'pasta', description: 'Pasta meals', is_active: true, image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_noodles', name: 'Noodles', slug: 'noodles', description: 'Noodle dishes', is_active: true, image_url: 'https://images.unsplash.com/photo-1612927601601-6638404737ce?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_beans', name: 'Beans', slug: 'beans', description: 'Beans meals', is_active: true, image_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_yam', name: 'Yam', slug: 'yam', description: 'Boiled and fried yam options', is_active: true, image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_plantain', name: 'Plantain', slug: 'plantain', description: 'Fried and boiled plantains', is_active: true, image_url: 'https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_swallow', name: 'Swallow', slug: 'swallow', description: 'Traditional swallows', is_active: true, image_url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_soups', name: 'Soups', slug: 'soups', description: 'Authentic Nigerian soups', is_active: true, image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_chicken', name: 'Chicken', slug: 'chicken', description: 'Grilled and fried chicken options', is_active: true, image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_beef', name: 'Beef', slug: 'beef', description: 'Beef options', is_active: true, image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fish', name: 'Fish', slug: 'fish', description: 'Fresh and fried fish options', is_active: true, image_url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_egg', name: 'Egg', slug: 'egg', description: 'Boiled and fried eggs', is_active: true, image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_snacks', name: 'Snacks', slug: 'snacks', description: 'Pastries and light snacks', is_active: true, image_url: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fast_food', name: 'Fast Food', slug: 'fast-food', description: 'Quick bites and fast food', is_active: true, image_url: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_drinks', name: 'Drinks', slug: 'drinks', description: 'Beverages and refreshments', is_active: true, image_url: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_fruits', name: 'Fruits', slug: 'fruits', description: 'Fresh fruit options', is_active: true, image_url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_desserts', name: 'Desserts', slug: 'desserts', description: 'Sweet treats and desserts', is_active: true, image_url: 'https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_coffee', name: 'Coffee', slug: 'coffee', description: 'Brewed coffee options', is_active: true, image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&q=80&w=300' },
  { id: 'cat_tea', name: 'Tea', slug: 'tea', description: 'Hot and cold tea drinks', is_active: true, image_url: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=300' },
];

async function withTimeout<T>(promise: Promise<T>, ms = 3500): Promise<T> {
  let timer: any;
  const timeoutPromise = new Promise<never>((_, reject) => {
    timer = setTimeout(() => reject(new Error('Firestore operation timeout')), ms);
  });
  try {
    return await Promise.race([promise, timeoutPromise]);
  } finally {
    clearTimeout(timer);
  }
}

export async function initializeDatabaseSeed() {
  try {
    // 1. Check if MTU seed already exists (with 3.5s timeout for offline resilience)
    const mtuDoc = await withTimeout(getDoc(doc(db, 'universities', 'uni_mtu')));
    
    if (mtuDoc.exists()) {
      console.log('Mountain Top University (MTU) seed data already present in Firestore.');
      return;
    }

    console.log('Initializing Mountain Top University (MTU) seed data in Firestore...');

    // 2. University: Mountain Top University
    await setDoc(doc(db, 'universities', FALLBACK_MTU_UNIVERSITY.id), FALLBACK_MTU_UNIVERSITY);

    // 3. Campus: Main Campus
    await setDoc(doc(db, 'campuses', FALLBACK_MTU_CAMPUS.id), FALLBACK_MTU_CAMPUS);

    // 4. MTU Food Facilities & Vendors
    for (const v of FALLBACK_MTU_VENDORS) {
      await setDoc(doc(db, 'vendors', v.id), v);
      await setDoc(doc(db, 'restaurants', v.id), {
        id: v.id,
        name: v.name,
        description: v.description || '',
        logo_url: v.logo_url,
        cover_image_url: v.cover_image_url,
        review_count: v.review_count || 0,
        rating: v.rating || 4.8,
        delivery_fee: 200,
        estimated_delivery_time: '10-20 min',
        minimum_order: 500,
        address: v.address,
        latitude: v.latitude,
        longitude: v.longitude,
        is_open: true,
        created_at: v.created_at
      });
    }

    // 5. Food Categories for MTU
    for (const c of FALLBACK_MTU_CATEGORIES) {
      await setDoc(doc(db, 'food_categories', c.id), c);
      await setDoc(doc(db, 'categories', c.id), c);
    }

    // 6. Food Menu Items for MTU
    for (const item of FALLBACK_MTU_MENU_ITEMS) {
      await setDoc(doc(db, 'menu_items', item.id), item);
    }

    console.log('Mountain Top University (MTU) baseline seed data successfully initialized.');
  } catch (error: any) {
    console.info('Firestore offline or connecting: using MTU offline local fallback data.');
  }
}


